In [1]:
import numpy as np

# X = (hours sleeping, hours studying)
X = np.array(([3,5],[5,1],[10,2]))
# y = Score on test
y = np.array((75,82,93))

# normalize
X= X/np.amax(X,axis=0)
y = y/100

In [2]:
class NeuralNetwork(object):
    def __init__(self):
        # Hyperparameters
        self.inputLayerSize = 2
        self.hiddenLayerSize = 3
        self.outputLayerSize = 1
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        #forward propagation
        self.Z2 = np.dot(X,self.W1)
        self.a2 = self.sigmoid(self.Z2)
        self.Z3 = np.dot(self.a2,self.W2)
        yHat = self.sigmoid(self.Z3)
        return yHat
        
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))


In [5]:
NN = NeuralNetwork()
yHat = NN.forward(X)
y

array([0.75, 0.82, 0.93])

In [4]:
yHat

array([[0.33090894],
       [0.42703822],
       [0.45157929]])

In [6]:
y-yHat

array([[0.52433806, 0.59433806, 0.70433806],
       [0.52773623, 0.59773623, 0.70773623],
       [0.51155087, 0.58155087, 0.69155087]])

In [5]:
import time
weightsToTry = np.linspace(-10,10,1000)
costs = np.zeros(1000)

startTime = time.time()

for i in range(1000):
    NN.W1[0,0] = weightsToTry[i]
    yHat = NN.forward(X)
    costs[i] = 0.5*sum((y-yHat)**2)

endTime = time.time()

timeElapsed = endTime-startTime
timeElapsed


In [6]:
import time

weightsToTry = np.linspace(-5,5,1000)
costs = np.zeros(1000)

startTime = time.process_time()
for i in range(1000):
    NN.W1[0,0] = weightsToTry[i]
    yHat = NN.forward(X)
    costs[i] = 0.5*sum((y-yHat)**2)
    
endTime = time.process_time()

In [5]:
import time

weightsToTry = np.linspace(-5,5,3)
costs = np.zeros(3)

startTime = time.process_time()
for i in range(3):
    NN.W1[0,0] = weightsToTry[i]
    yHat = NN.forward(X)
    costs[i] = 0.5*sum((y-yHat)**2)
    
endTime = time.process_time()